DotnetEfCore2/DotnetEfCore2/Models/ErrorViewModel.cs
namespace DotnetEfCore2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotnetEfCore2/DotnetEfCore2/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using DotnetEfCore2.DataContext;

namespace DotnetEfCore2.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context)
        { _context = context; }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<CategoryEntity> categories = _context.CategoryEntities.ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            CategoryEntity category = _context.CategoryEntities.Find(id);
            return View(category);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("CategoryCode, CategoryName, Description")] CategoryEntity request)
        {
            // add ke entity
            _context.CategoryEntities.Add(request);
            // commit to database
            _context.SaveChanges();

            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var entity = _context.CategoryEntities.Find(id);
            return View(entity);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var entity = _context.CategoryEntities.Find(id);
            if (entity == null)
            {
                return Redirect("GetAll");
            }
            // remove from entity
            _context.CategoryEntities.Remove(entity);
            // commit to database
            _context.SaveChanges();
            return RedirectToAction("GetAll");
        }

        [HttpPost]
        public IActionResult Update([Bind("Id,CategoryCode, CategoryName, Description")] CategoryEntity request)
        {
            // update entity
            _context.CategoryEntities.Update(request);
            // commit to database
            _context.SaveChanges();
            return Redirect("GetAll");
        }

    }
}

DotnetEfCore2/DotnetEfCore2/Controllers/CompanyController.cs
using DotnetEfCore2.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotnetEfCore2.Controllers
{
    public class CompanyController : Controller
    {

        private readonly ApplicationDbContext _context;
        public CompanyController(ApplicationDbContext context)
        { _context = context; }

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<CompanyEntity> companies = _context.CompanyEntities.ToList();
            return View(companies);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            CompanyEntity company = _context.CompanyEntities.Find(id);
            return View(company);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("CompanyName, Logo, Address, Telp")] CompanyEntity request)
        {
            // add ke entity
            _context.CompanyEntities.Add(request);
            // commit to database
            _context.SaveChanges();

            return Redirect("GetAll");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var entity = _context.CompanyEntities.Find(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id,CompanyName, Logo, Address, Telp")] CompanyEntity request)
        {
            // update entity
            _context.CompanyEntities.Update(request);
            // commit to database
            _context.SaveChanges();
            return Redirect("GetAll");
        }


        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var entity = _context.CompanyEntities.Find(id);
            if (entity == null)
            {
                return Redirect("GetAll");
            }
            // remove from entity
            _context.CompanyEntities.Remove(entity);
            // commit to database
            _context.SaveChanges();
            return RedirectToAction("GetAll");
        }
    }
}

DotnetEfCore2/DotnetEfCore2/Controllers/HomeController.cs
using DotnetEfCore2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DotnetEfCore2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Category()
        {
            return View();
        }
    }
}

DotnetEfCore2/DotnetEfCore2/Views/Category/Add.cshtml
@model DotnetEfCore2.DataContext.CategoryEntity

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Add New Category</h2>
<form asp-controller="Category" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

DotnetEfCore2/DotnetEfCore2/Views/Category/Details.cshtml
@model DotnetEfCore2.DataContext.CategoryEntity

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Detail Category</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Code</th>
        <td>@Model.CategoryCode</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
</table>

DotnetEfCore2/DotnetEfCore2/Views/Category/Edit.cshtml
@model DotnetEfCore2.DataContext.CategoryEntity

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Edit Category</h2>
<form asp-controller="Category" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CategoryCode"></label>
        <input asp-for="CategoryCode" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="CategoryName"></label>
        <input asp-for="CategoryName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

DotnetEfCore2/DotnetEfCore2/Views/Category/GetAll.cshtml
@model IEnumerable<DotnetEfCore2.DataContext.CategoryEntity>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Category Get All</h2>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Code</th>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.CategoryCode</td>
                <td>@item.CategoryName</td>
                <td>@item.Description</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DotnetEfCore2/DotnetEfCore2/Views/Company/Add.cshtml
@model DotnetEfCore2.DataContext.CompanyEntity

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Add New Company</h2>
<form asp-controller="Company" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Logo"></label>
        <input asp-for="Logo" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Telp"></label>
        <input asp-for="Telp" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

DotnetEfCore2/DotnetEfCore2/Views/Company/Details.cshtml
@model DotnetEfCore2.DataContext.CompanyEntity

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Detail Company</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Company Name</th>
        <td>@Model.CompanyName</td>
    </tr>
    <tr>
        <th>Logo</th>
        <td>@Model.Logo</td>
    </tr>
    <tr>
        <th>Address</th>
        <td>@Model.Address</td>
    </tr>
    <tr>
        <th>Telp</th>
        <td>@Model.Telp</td>
    </tr>
</table>

DotnetEfCore2/DotnetEfCore2/Views/Company/Edit.cshtml
@model DotnetEfCore2.DataContext.CompanyEntity

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Edit Company</h2>
<form asp-controller="Company" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="CompanyName"></label>
        <input asp-for="CompanyName" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Logo"></label>
        <input asp-for="Logo" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Telp"></label>
        <input asp-for="Telp" class="form-control" />
    </div>
    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

DotnetEfCore2/DotnetEfCore2/Views/Company/GetAll.cshtml
@model IEnumerable<DotnetEfCore2.DataContext.CompanyEntity>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Company Get All</h2>
<a asp-action="Add" class="btn btn-sm btn-primary m-md-4">Add Company</a>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>Company Name</th>
            <th>Logo</th>
            <th>Address</th>
            <th>Telp</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.CompanyName</td>
                <td>@item.Logo</td>
                <td>@item.Address</td>
                <td>@item.Telp</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-success">View</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DotnetEfCore2/DotnetEfCore2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotnetEfCore2/DotnetEfCore2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotnetEfCore2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotnetEfCore2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotnetEfCore2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="GetAll">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="GetAll">Company</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DotnetEfCore2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>